name: 'Get branch name by PR'
description: 'Get the name of a branch by either running this action in the context of a PR, or supplying a pull request ID'
inputs:
  repo-token:
    description: 'GITHUB_TOKEN secret'
    required: true
  pr-id:
    description: 'Pull Request ID'
    required: false
outputs:
  branch:
    description: 'The branch we found via the PR'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
